---
# - name: Include a playbook from a collection
#   ansible.builtin.import_playbook: opentoucan.infrastructure.postgres
- name: Fail if molecule group is missing
  hosts: localhost
  tasks:
    - name: Print some info
      ansible.builtin.debug:
        msg: "{{ groups }}"

    - name: Download gencert
      ansible.builtin.shell:
        cd /tmp
        && wget https://github.com/minio/certgen/releases/download/v1.3.0/certgen-linux-amd64 \
        && chmod +x certgen-linux-amd64 \
        && mkdir -p /minio/certs
        && ./certgen-linux-amd64 -host "127.0.0.1,localhost,minio"
        && mv private.key public.crt /minio/certs
      changed_when: "'molecule-idempotence-notest' not in ansible_skip_tags"

    - name: Create minio container for pgbackrest
      community.docker.docker_container:
        name: minio
        image: minio/minio:latest
        state: started
        command: server /data --certs-dir /certs
        log_driver: json-file
        env:
          MINIO_ROOT_USER: minioadmin
          MINIO_ROOT_PASSWORD: minioadmin
        ports:
          - 9000:9000
          - 9001:9001
        networks:
          - name: molecule
        mounts:
          - type: bind
            source: /minio/certs
            target: /certs
      changed_when: "'molecule-idempotence-notest' not in ansible_skip_tags"

    - name: Create minio buckets
      community.docker.docker_container:
        name: bucket-creation
        image: minio/mc:latest
        state: started
        entrypoint: /bin/sh
        command: -c "mc alias set myminio https://minio:9000 minioadmin minioadmin --insecure && mc mb myminio/pgbackrest --insecure && mc anonymous set public myminio/pgbackrest --insecure"
        log_driver: json-file
        networks:
          - name: molecule
      changed_when: "'molecule-idempotence-notest' not in ansible_skip_tags"

- name: Converge
  hosts: all
  # We disable gather facts because it would fail due to our container not
  # having python installed. This will not prevent use from running 'raw'
  # commands. Most molecule users are expected to use containers that already
  # have python installed in order to avoid notable delays installing it.
  gather_facts: false
  tasks:
    - name: Install gnupg
      ansible.builtin.apt:
        name: gnupg
        state: present
        update_cache: true

- name: Postgres Playbook
  import_playbook: ../../postgres.yml
