---
- name: Verify
  hosts: postgres
  become: false
  gather_facts: false

  tasks:
    - name: Check port 5432
      ansible.builtin.wait_for:
        port: 5432

    - name: Check PSQL is ready status
      ansible.builtin.command: pg_isready -d molecule
      register: postgres_ready
      changed_when: postgres_ready.rc != 0
