---
- name: Verify
  hosts: postgres
  become: no
  gather_facts: no

  tasks:
    - name: Check port 5432
      ansible.builtin.wait_for:
        port: 5432

    - name: Check PSQL is ready status
      ansible.builtin.command: pg_isready -d molecule
