---
extends: default
rules:
  truthy:
    allowed-values: ["true", "false", "on", "off", "yes", "no"]
  line-length:
    max: 200
  comments:
    min-spaces-from-content: 1
  comments-indentation: false
  braces:
    max-spaces-inside: 1
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
